# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1159, 816)
        self.gridWidget = QtWidgets.QWidget(Dialog)
        self.gridWidget.setGeometry(QtCore.QRect(70, 160, 1021, 641))
        self.gridWidget.setMaximumSize(QtCore.QSize(1021, 641))
        self.gridWidget.setObjectName("gridWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.camera = QtWidgets.QLabel(self.gridWidget)
        self.camera.setMaximumSize(QtCore.QSize(498, 308))
        self.camera.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.camera.setToolTipDuration(-1)
        self.camera.setStyleSheet("")
        self.camera.setFrameShape(QtWidgets.QFrame.Box)
        self.camera.setFrameShadow(QtWidgets.QFrame.Raised)
        self.camera.setLineWidth(3)
        self.camera.setScaledContents(True)
        self.camera.setObjectName("camera")
        self.gridLayout.addWidget(self.camera, 0, 0, 1, 1)
        self.prt_sc = QtWidgets.QLabel(self.gridWidget)
        self.prt_sc.setMaximumSize(QtCore.QSize(498, 307))
        self.prt_sc.setStyleSheet("")
        self.prt_sc.setFrameShape(QtWidgets.QFrame.Box)
        self.prt_sc.setFrameShadow(QtWidgets.QFrame.Raised)
        self.prt_sc.setLineWidth(3)
        self.prt_sc.setText("")
        self.prt_sc.setPixmap(QtGui.QPixmap("../../../Pictures/Thành Long-20230411T113238Z-001/Thành Long/IMG_1842.PNG"))
        self.prt_sc.setScaledContents(True)
        self.prt_sc.setObjectName("prt_sc")
        self.gridLayout.addWidget(self.prt_sc, 1, 0, 1, 1)
        self.info = QtWidgets.QWidget(self.gridWidget)
        self.info.setObjectName("info")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.info)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_biensoxe = QtWidgets.QLabel(self.info)
        self.label_biensoxe.setMaximumSize(QtCore.QSize(498, 98))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_biensoxe.setFont(font)
        self.label_biensoxe.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.506, fy:0.5, stop:0.9375 rgba(0, 0, 0, 120));\n"
"color: white;\n"
"")
        self.label_biensoxe.setFrameShape(QtWidgets.QFrame.Box)
        self.label_biensoxe.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_biensoxe.setLineWidth(3)
        self.label_biensoxe.setAlignment(QtCore.Qt.AlignCenter)
        self.label_biensoxe.setObjectName("label_biensoxe")
        self.verticalLayout.addWidget(self.label_biensoxe)
        self.label_ngaygio = QtWidgets.QLabel(self.info)
        self.label_ngaygio.setMaximumSize(QtCore.QSize(495, 98))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_ngaygio.setFont(font)
        self.label_ngaygio.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.506, fy:0.5, stop:0.9375 rgba(0, 0, 0, 120));\n"
"color: white;\n"
"")
        self.label_ngaygio.setFrameShape(QtWidgets.QFrame.Box)
        self.label_ngaygio.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_ngaygio.setLineWidth(3)
        self.label_ngaygio.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ngaygio.setObjectName("label_ngaygio")
        self.verticalLayout.addWidget(self.label_ngaygio)
        self.label_sotien = QtWidgets.QLabel(self.info)
        self.label_sotien.setMaximumSize(QtCore.QSize(495, 98))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_sotien.setFont(font)
        self.label_sotien.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.506, fy:0.5, stop:0.9375 rgba(0, 0, 0, 120));\n"
"color: white;\n"
"")
        self.label_sotien.setFrameShape(QtWidgets.QFrame.Box)
        self.label_sotien.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_sotien.setLineWidth(3)
        self.label_sotien.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sotien.setObjectName("label_sotien")
        self.verticalLayout.addWidget(self.label_sotien)
        self.gridLayout.addWidget(self.info, 0, 1, 1, 1)
        self.BTN = QtWidgets.QWidget(self.gridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN.sizePolicy().hasHeightForWidth())
        self.BTN.setSizePolicy(sizePolicy)
        self.BTN.setMaximumSize(QtCore.QSize(497, 307))
        self.BTN.setObjectName("BTN")
        self.CAPTURE_BTN = QtWidgets.QPushButton(self.BTN)
        self.CAPTURE_BTN.setGeometry(QtCore.QRect(10, 50, 231, 221))
        self.CAPTURE_BTN.setMaximumSize(QtCore.QSize(231, 221))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.CAPTURE_BTN.setFont(font)
        self.CAPTURE_BTN.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.CAPTURE_BTN.setStyleSheet("color:white;\n"
"border-radius:50px;\n"
"border-image: url(:/image/gradient.jpg);\n"
"\n"
"")
        self.CAPTURE_BTN.setObjectName("CAPTURE_BTN")
        self.PASS_BTN = QtWidgets.QPushButton(self.BTN)
        self.PASS_BTN.setGeometry(QtCore.QRect(260, 50, 231, 221))
        self.PASS_BTN.setMaximumSize(QtCore.QSize(231, 221))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.PASS_BTN.setFont(font)
        self.PASS_BTN.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PASS_BTN.setStyleSheet("color:white;\n"
"border-radius:50px;\n"
"border-image: url(:/image/gradient.jpg);")
        self.PASS_BTN.setObjectName("PASS_BTN")
        self.gridLayout.addWidget(self.BTN, 1, 1, 1, 1)
        self.container = QtWidgets.QLabel(Dialog)
        self.container.setGeometry(QtCore.QRect(70, 30, 1021, 771))
        self.container.setMaximumSize(QtCore.QSize(1021, 771))
        font = QtGui.QFont()
        font.setFamily("Microsoft New Tai Lue")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.container.setFont(font)
        self.container.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.container.setStyleSheet("border-image: url(:/image/gradient.jpg);\n"
"border-top-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"color: white;\n"
"")
        self.container.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.container.setWordWrap(False)
        self.container.setIndent(-1)
        self.container.setObjectName("container")
        self.container.raise_()
        self.gridWidget.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.camera.setText(_translate("Dialog", "camera xe vao"))
        self.label_biensoxe.setText(_translate("Dialog", "51H-999.99"))
        self.label_ngaygio.setText(_translate("Dialog", "04/05/2023 3:33:46"))
        self.label_sotien.setText(_translate("Dialog", "4000"))
        self.CAPTURE_BTN.setText(_translate("Dialog", "CAPTURE"))
        self.PASS_BTN.setText(_translate("Dialog", "PASS"))
        self.container.setText(_translate("Dialog", "Parking Car Management"))
import res


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
